
" ===Common Setting===
colorscheme delek

syntax on
filetype plugin indent on
let mapleader = ","
set ignorecase
set incsearch
set nonumber
set nocompatible " not compatible w/ vi
set cursorline " highlight current line


" normal file type
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab

" ===Common Setting End===

" ===FileType===

autocmd FileType sh setlocal tabstop=4 softtabstop=4 shiftwidth=4
autocmd Filetype html,javascript setlocal tabstop=2 softtabstop=2 shiftwidth=2 tw=80 expandtab

autocmd FileType c,cpp : set foldmethod=syntax
autocmd FileType c,cpp : set nofoldenable
" google
autocmd FileType c,cpp setlocal tabstop=2 softtabstop=2 shiftwidth=2 tw=80 expandtab

" gitcommit
autocmd FileType gitcommit setlocal tw=72 cc=+1 spell

" ===FileType End===

" --- VIM-PLUG SETUP ---
call plug#begin('~/.vim/plugged')

" Your list of plugins

" file explorer
Plug 'scrooloose/nerdtree'

" code tags
Plug 'majutsushi/tagbar'

" status/tabline
Plug 'vim-airline/vim-airline'

" ack
Plug 'mileszs/ack.vim'

" as name
Plug 'bronson/vim-trailing-whitespace'

" Install vim-codefmt and its dependencies
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
" Also add Glaive, which is used to configure codefmt's maktaba flags. See
" " `:help :Glaive` for usage.
Plug 'google/vim-glaive'

call plug#end()
" --- END VIM-PLUG SETUP ---


let NERDTreeShowHidden=1
nmap <leader>f :NERDTreeToggle


nmap tl :TagbarToggle
let g:tagbar_left=1
let g:tagbar_sort=0


let g:airline#extensions#tabline#enabled = 1


nnoremap <silent> <F7> :Ack<CR>

